from . import res_users
from . import res_partner
from . import sale
from . import account_invoice
from . import product
from . import purchase_order
from . import poi_stock_reservation_lot
from . import stock
from . import stock_move_line
from . import stock_picking
from . import crm_lead
from . import sale_type
from . import poi_stock_reservation_lot
from . import sale_contract
from . import plate
#from . import product_images
from . import account_payment_request
from . import pricelist
from . import res_partner_integration
from . import stock_request
from . import account
#from . import invoice_legacy
