{
    'name': 'Reportes a Medida para Toyosa S.A.',
    'version': '11.0.1.0.0',
    "author": "PoiesisConsulting",
    'category': 'Reports',
    'website': 'http://www.poiesisconsulting.com',
    'summary': 'Reportes',
    'depends': [
        'poi_x_toyosa',
        # 'poi_trace_stock_account',
        'sale',
        # 'poi_materialized_view',
        'poi_sale_report_advanced',
        'poi_ai_money_exchange',
    ],
    'data': [
        'report/img_report.xml',
        'report/img_sale_order.xml',
        'report/sale_order_report_toy.xml',
        'report/sale_order_report_hino.xml',
        'report/sale_order_report_neu.xml',
        'report/sale_order_report_kub.xml',
        'report/sale_order_report_rep.xml',
        'report/sale_order_report_unic.xml',
        'report/sale_order_report_volvo.xml',
        'report/sale_order_report_yam.xml',
        'report/sale_order_base.xml',
        'report/sale_contract_report_toy.xml',
        'report/invoice_report_toy.xml',
        'report/invoice_template.xml',
        'report/invoice_report_mrva.xml',
        'report/invoice_report_mot.xml',
        'report/invoice_report_neu.xml',
        'report/invoice_report_ppav.xml',
        'report/invoice_analysis.xml',
        'report/traffic_analysis.xml',
        'report/neumaticos_booking.xml',
        'report/invoice_report_cif.xml',
        'report/invoice_report_maq.xml',
        'report/invoice_report_oae.xml',
        'report/invoice_base.xml',
        'report/sale_order_report_adenda.xml',
        'report/checklist_report.xml',
        'report/nota_report.xml',
        'report/hojan_report.xml',
        'report/wallet_report.xml',
        'report/bag_vehicles_report.xml',
        'report/bag_vehicles_cc_report.xml',
        'report/sale_move_report.xml',
        # 'report/account_asset_report_2.xml',
        'report/diary_book.xml',
        'report/invoice_analysis_lot.xml',
        'wizard/bag_vehicles_cc_wizard.xml',
        # 'report/account_chasis_report.xml',
        'views/sale_report_config.xml',
        'views/bag_vehicles_config.xml',
        'wizard/wallet_wizard.xml',
        'wizard/bag_vehicles_wizard.xml',
        'wizard/sale_move_wizard.xml',
        'wizard/diary_book_wiz.xml',
        'data/data.xml',
        'data/data_wallet_reports.xml',
        'security/ir.model.access.csv',
    ],
    'installable': True,
    'images': [
        '/static/description/images/toyosa_logo1.JPG',
        '/static/description/images/toyosa_logo2.png',
        '/static/description/images/toyosa_logo3.png',
    ],
}
