{
    'name': 'Implementaciones Toyosa S.A.',
    'version': '11.0.1.0.0',
    "author": "Poiesis Consulting",
    'category': 'Purchase Management',
    'website': 'http://www.poiesisconsulting.com',
    'summary': 'Adecuaciones especificas a Toyosa',
    'depends': [
        'analytic',
        'sale',
        'sales_team',
        'stock',
        'purchase',
        'product_expiry',
        'poi_account_advanced',
        'poi_purchase_imports',
        'poi_sale_order_lot_selection',
        'poi_bol_base',
        'poi_crm_traffic',
        'poi_partner_firstname',
        'poi_crm_lead',
        'poi_auth_base',
        'poi_sale_payment_advanced',
        #'poi_account_reports',
        'poi_stock_request',
        'poi_bol_cc',
        'poi_warehouse',
        'poi_sale_discounts',
        'poi_sale_report_advanced',
        #'poi_support',
        'website',
        'poi_account_analytic',
    ],
    'data': [
        'security/sale_security.xml',
        'security/toyosa_security.xml',
        'wizard/poi_reservation_wizard_view.xml',
        'wizard/sale_cancel.xml',
        'wizard/sale_order_extra.xml',
        'views/res_partner.xml',
        'views/sale_type.xml',
        'views/product_view.xml',
        'wizard/update_fob_picking_view.xml',
        'views/purchase_order_view.xml',
        'views/purchase_imports_menu_toyosa_view.xml',
        'views/stock_production_lot_view.xml',
        'views/cuadro_prioridades_nacionalizacion_view.xml',
        'views/account_invoice_view.xml',
        'views/estado_importaciones_view.xml',
        'views/bolsa_vehiculos_view.xml',
        'views/crm_lead.xml',
        'views/sale.xml',
        'views/sale_contract.xml',
        'views/plate.xml',
        'views/plate_wallet.xml',
        'views/poi_stock_request_view.xml',
        'views/stock_picking_view.xml',
        'views/pricelist.xml',
        'report/chasis_inventory_report_view.xml',
        'report/stock_lot_incidence_report_view.xml',
        #'report/report_kardex_chasis_view.xml',
        'report/chasis_payment_history_report_view.xml',
        'views/report_stockpicking_operations.xml',
        'views/stock_view.xml',
        #'report/purchase_report_toyosa_view.xml',
        #'wizard/report_kardex_chasis_wizard_view.xml',
        #'wizard/update_ed_view.xml',
        #'views/cuadro_reservas_view.xml',
        'views/account_payment_request_view.xml',
        'views/res_users.xml',
        #'views/invoice_legacy.xml',
        #'picking_report.xml',
        'data/toyosa_sequence.xml',
        #'data/mail_template_data.xml',
        #'data/base_config.xml',
        'data/sale_auth.xml',
        'data/sale_data.xml',
        #'views/comercial_view.xml',
        #'views/account_view.xml',
        'security/ir.model.access.csv',
        #'data/run_install_function.yml',
        'views/res_partner_integration_view.xml',
        #'views/webclient_templates.xml',
        'static/src/xml/base_view.xml',
        'report/chasis_landed_cost_report_view.xml',
        #'report/inventory_speed_report_view.xml',
        #'report/inventory_speed_previsto_report_view.xml',
        #'report/inventory_dui_report_view.xml',
        #'views/menu_config_sup.xml',
        #'data/reserve_data.xml',
    ],
    'installable': True,
    'images': [
        '/static/description/images/toyosa_logo1.JPG',
        '/static/description/images/toyosa_logo2.png',
        '/static/description/images/toyosa_logo3.png',
    ],
}
