# -*- encoding: utf-8 -*-
{
    'name': "Adaptaciones Landicorp Implelab Reportes",
    'version': '9.0.0',
    'summary': 'Adaptaciones Landicorp Implelab Reportes',
    'category': 'Other',
    'description': """""",
    'author': 'Poiesis Consulting',
    "website": "http://www.poiesisconsulting.com",
    "depends" : ['sale', 'stock', 'purchase', 'poi_x_implelab', 'report', 'report_aeroo'],
    'data': [
            'views/purchase.xml',
            'views/sale.xml',
            'views/res_partner.xml',
            'report/imp_img.xml',
             'report/proforma.xml',
             'report/picking_left.xml',
             'report/purchase.xml',
             'report/purchase_eled.xml',
             'report/purchase_MBP.xml',
             'report/purchase_g.xml',
             'report/purchase_nunc.xml',
             'report/purchase_html.xml',
             'report/purchase_eled_html.xml',
             'report/purchase_MBP_html.xml',
             'report/purchase_g_html.xml',
             'report/purchase_nunc_html.xml',
             'report/purchase_MBS.xml',
             'report/basic_invoice.xml',
             'report/picking_left_html.xml',
             'report/proforma_html.xml',
             'report/invoice.xml',
             'report/base_ext_header.xml',
             'report/proforma_mbp.xml',
             ],
    'qweb': [],

    'installable': False,
    'application'   : True,
    'auto_install'  : False,
}
