from . import hr
from . import hr_advance
from . import hr_loan
from . import hr_form110
from . import hr_others
from . import hr_planing
from . import hr_bio
from . import hr_payroll
from . import hr_finiquito
